// Code generated by scripts/generate_openapi_go.py. DO NOT EDIT.
// Source: docs/openapi.v1.yaml

package apiv1

type ExpertType string

const (
	ExpertTypeFixedIncome ExpertType = "fixed_income"
	ExpertTypeMacro ExpertType = "macro"
	ExpertTypeEquity ExpertType = "equity"
)

type JobStatus string

const (
	JobStatusQueued JobStatus = "queued"
	JobStatusRunning JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
	JobStatusFailed JobStatus = "failed"
	JobStatusCanceled JobStatus = "canceled"
	JobStatusExpired JobStatus = "expired"
)

type SubmitBriefRequest struct {
	TenantId *string `json:"tenant_id,omitempty"`
	ProjectId *string `json:"project_id,omitempty"`
	ExpertId string `json:"expert_id"`
	ExpertName *string `json:"expert_name,omitempty"`
	ExpertType *ExpertType `json:"expert_type,omitempty"`
	Date string `json:"date"`
	Timezone *string `json:"timezone,omitempty"`
	Callback *CallbackConfig `json:"callback,omitempty"`
	Inference *InferenceConfig `json:"inference,omitempty"`
	Options *BriefOptions `json:"options,omitempty"`
}

type CallbackConfig struct {
	Url string `json:"url"`
	Signing *CallbackSigning `json:"signing,omitempty"`
}

type CallbackSigning struct {
	Algorithm string `json:"algorithm"`
	SecretRef string `json:"secret_ref"`
}

type InferenceConfig struct {
	Provider *string `json:"provider,omitempty"`
	CredentialMode *string `json:"credential_mode,omitempty"`
	Token *string `json:"token,omitempty"`
}

type BriefOptions struct {
	MaxSources *int `json:"max_sources,omitempty"`
	Language *string `json:"language,omitempty"`
}

type SubmitBriefResponse struct {
	JobId string `json:"job_id"`
	TenantId string `json:"tenant_id"`
	ProjectId string `json:"project_id"`
	ExpertId string `json:"expert_id"`
	ExpertName *string `json:"expert_name,omitempty"`
	ExpertType *ExpertType `json:"expert_type,omitempty"`
	Status JobStatus `json:"status"`
	SubmittedAt string `json:"submitted_at"`
	RequestId *string `json:"request_id,omitempty"`
}

type JobStatusResponse struct {
	JobId string `json:"job_id"`
	TenantId string `json:"tenant_id"`
	ProjectId string `json:"project_id"`
	ExpertId string `json:"expert_id"`
	ExpertName *string `json:"expert_name,omitempty"`
	ExpertType *ExpertType `json:"expert_type,omitempty"`
	Status JobStatus `json:"status"`
	Progress *int `json:"progress,omitempty"`
	SubmittedAt string `json:"submitted_at"`
	UpdatedAt string `json:"updated_at"`
	Attempt int `json:"attempt"`
}

type JobResultResponse struct {
	JobId string `json:"job_id"`
	TenantId string `json:"tenant_id"`
	ProjectId string `json:"project_id"`
	ExpertId string `json:"expert_id"`
	ExpertName *string `json:"expert_name,omitempty"`
	ExpertType *ExpertType `json:"expert_type,omitempty"`
	Status string `json:"status"`
	Result ExpertResult `json:"result"`
}

type JobDeliveriesResponse struct {
	JobId string `json:"job_id"`
	TenantId string `json:"tenant_id"`
	ProjectId string `json:"project_id"`
	Deliveries []WebhookDeliveryRecord `json:"deliveries"`
}

type WebhookDeliveryRecord struct {
	DeliveryId string `json:"delivery_id"`
	EventId string `json:"event_id"`
	EventType string `json:"event_type"`
	JobId *string `json:"job_id,omitempty"`
	CallbackUrl string `json:"callback_url"`
	Attempt int `json:"attempt"`
	MaxAttempts int `json:"max_attempts"`
	Success bool `json:"success"`
	HttpStatus *int `json:"http_status,omitempty"`
	Error *string `json:"error,omitempty"`
	RequestedAt string `json:"requested_at"`
	DurationMs int `json:"duration_ms"`
	NextRetryAt *string `json:"next_retry_at,omitempty"`
	PayloadSha256 string `json:"payload_sha256"`
}

type QueryRequest struct {
	TenantId *string `json:"tenant_id,omitempty"`
	ProjectId *string `json:"project_id,omitempty"`
	ExpertId string `json:"expert_id"`
	ExpertName *string `json:"expert_name,omitempty"`
	ExpertType *ExpertType `json:"expert_type,omitempty"`
	Question string `json:"question"`
	TimeWindow *TimeWindow `json:"time_window,omitempty"`
	Inference *InferenceConfig `json:"inference,omitempty"`
}

type QueryResponse = ExpertResult

type TimeWindow struct {
	Start string `json:"start"`
	End string `json:"end"`
}

type ExpertResult struct {
	Title *string `json:"title,omitempty"`
	Answer string `json:"answer"`
	Confidence float64 `json:"confidence"`
	FreshnessCutoff string `json:"freshness_cutoff"`
	References []ReferenceRecord `json:"references,omitempty"`
	Citations []Citation `json:"citations,omitempty"`
	Limitations []string `json:"limitations,omitempty"`
}

type ReferenceRecord map[string]any

type Citation struct {
	SourceId string `json:"source_id"`
	SourceName *string `json:"source_name,omitempty"`
	Title string `json:"title"`
	Url *string `json:"url,omitempty"`
	PublishedAt string `json:"published_at"`
}

type ExpertCapabilitiesResponse struct {
	Experts []ExpertCapability `json:"experts"`
}

type ExpertCapability struct {
	ExpertId string `json:"expert_id"`
	ExpertName string `json:"expert_name"`
	ExpertType ExpertType `json:"expert_type"`
	Supports []string `json:"supports"`
	Status string `json:"status"`
	Version string `json:"version"`
}

type Problem struct {
	Type string `json:"type"`
	Title string `json:"title"`
	Status int `json:"status"`
	Detail *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}
