// Code generated by scripts/generate_openapi_go.py. DO NOT EDIT.
// Source: docs/openapi.v1.yaml

package cova

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"cova/pkg/apiv1"
)

type Client struct {
	BaseURL    string
	HTTPClient *http.Client
	Token      string
}

type ClientOption func(*Client)

func WithHTTPClient(httpClient *http.Client) ClientOption {
	return func(c *Client) {
		if httpClient != nil {
			c.HTTPClient = httpClient
		}
	}
}

func WithBearerToken(token string) ClientOption {
	return func(c *Client) { c.Token = token }
}

func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {
	baseURL = strings.TrimSpace(baseURL)
	if baseURL == "" {
		return nil, fmt.Errorf("baseURL is required")
	}
	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid baseURL: %w", err)
	}
	c := &Client{
		BaseURL:    strings.TrimRight(u.String(), "/"),
		HTTPClient: http.DefaultClient,
	}
	for _, opt := range opts {
		opt(c)
	}
	if c.HTTPClient == nil {
		c.HTTPClient = http.DefaultClient
	}
	return c, nil
}

func (c *Client) SubmitBriefJob(ctx context.Context, req apiv1.SubmitBriefRequest, requestID string, idempotencyKey string, xTenantId string, xProjectId string) (*apiv1.SubmitBriefResponse, *apiv1.Problem, error) {
	path := "/v1/assistant/jobs"
	headers := map[string]string{}
	if requestID != "" {
		headers["X-Request-Id"] = requestID
	}
	if idempotencyKey != "" {
		headers["Idempotency-Key"] = idempotencyKey
	}
	status, body, problem, err := c.doJSON(ctx, "POST", path, req, headers)
	if err != nil {
		return nil, nil, err
	}
	if status == http.StatusAccepted {
		var outBody apiv1.SubmitBriefResponse
		if err := json.Unmarshal(body, &outBody); err != nil {
			return nil, nil, fmt.Errorf("decode success response: %w", err)
		}
		return &outBody, nil, nil
	}
	if problem != nil {
		return nil, problem, nil
	}
	return nil, nil, fmt.Errorf("unexpected status code: %d", status)
}

func (c *Client) GetJobStatus(ctx context.Context, jobID string, requestID string, xTenantId string, xProjectId string) (*apiv1.JobStatusResponse, *apiv1.Problem, error) {
	path := fmt.Sprintf("/v1/assistant/jobs/%s", jobID)
	headers := map[string]string{}
	if requestID != "" {
		headers["X-Request-Id"] = requestID
	}
	status, body, problem, err := c.doJSON(ctx, "GET", path, nil, headers)
	if err != nil {
		return nil, nil, err
	}
	if status == http.StatusOK {
		var outBody apiv1.JobStatusResponse
		if err := json.Unmarshal(body, &outBody); err != nil {
			return nil, nil, fmt.Errorf("decode success response: %w", err)
		}
		return &outBody, nil, nil
	}
	if problem != nil {
		return nil, problem, nil
	}
	return nil, nil, fmt.Errorf("unexpected status code: %d", status)
}

func (c *Client) GetJobResult(ctx context.Context, jobID string, requestID string, xTenantId string, xProjectId string) (*apiv1.JobResultResponse, *apiv1.Problem, error) {
	path := fmt.Sprintf("/v1/assistant/jobs/%s/result", jobID)
	headers := map[string]string{}
	if requestID != "" {
		headers["X-Request-Id"] = requestID
	}
	status, body, problem, err := c.doJSON(ctx, "GET", path, nil, headers)
	if err != nil {
		return nil, nil, err
	}
	if status == http.StatusOK {
		var outBody apiv1.JobResultResponse
		if err := json.Unmarshal(body, &outBody); err != nil {
			return nil, nil, fmt.Errorf("decode success response: %w", err)
		}
		return &outBody, nil, nil
	}
	if problem != nil {
		return nil, problem, nil
	}
	return nil, nil, fmt.Errorf("unexpected status code: %d", status)
}

func (c *Client) GetJobDeliveries(ctx context.Context, jobID string, requestID string, xTenantId string, xProjectId string) (*apiv1.JobDeliveriesResponse, *apiv1.Problem, error) {
	path := fmt.Sprintf("/v1/assistant/jobs/%s/deliveries", jobID)
	headers := map[string]string{}
	if requestID != "" {
		headers["X-Request-Id"] = requestID
	}
	status, body, problem, err := c.doJSON(ctx, "GET", path, nil, headers)
	if err != nil {
		return nil, nil, err
	}
	if status == http.StatusOK {
		var outBody apiv1.JobDeliveriesResponse
		if err := json.Unmarshal(body, &outBody); err != nil {
			return nil, nil, fmt.Errorf("decode success response: %w", err)
		}
		return &outBody, nil, nil
	}
	if problem != nil {
		return nil, problem, nil
	}
	return nil, nil, fmt.Errorf("unexpected status code: %d", status)
}

func (c *Client) CancelJob(ctx context.Context, jobID string, requestID string, xTenantId string, xProjectId string) (*apiv1.JobStatusResponse, *apiv1.Problem, error) {
	path := fmt.Sprintf("/v1/assistant/jobs/%s/cancel", jobID)
	headers := map[string]string{}
	if requestID != "" {
		headers["X-Request-Id"] = requestID
	}
	status, body, problem, err := c.doJSON(ctx, "POST", path, nil, headers)
	if err != nil {
		return nil, nil, err
	}
	if status == http.StatusAccepted {
		var outBody apiv1.JobStatusResponse
		if err := json.Unmarshal(body, &outBody); err != nil {
			return nil, nil, fmt.Errorf("decode success response: %w", err)
		}
		return &outBody, nil, nil
	}
	if problem != nil {
		return nil, problem, nil
	}
	return nil, nil, fmt.Errorf("unexpected status code: %d", status)
}

func (c *Client) ReplayJob(ctx context.Context, jobID string, requestID string, xTenantId string, xProjectId string) (*apiv1.JobStatusResponse, *apiv1.Problem, error) {
	path := fmt.Sprintf("/v1/assistant/jobs/%s/replay", jobID)
	headers := map[string]string{}
	if requestID != "" {
		headers["X-Request-Id"] = requestID
	}
	status, body, problem, err := c.doJSON(ctx, "POST", path, nil, headers)
	if err != nil {
		return nil, nil, err
	}
	if status == http.StatusAccepted {
		var outBody apiv1.JobStatusResponse
		if err := json.Unmarshal(body, &outBody); err != nil {
			return nil, nil, fmt.Errorf("decode success response: %w", err)
		}
		return &outBody, nil, nil
	}
	if problem != nil {
		return nil, problem, nil
	}
	return nil, nil, fmt.Errorf("unexpected status code: %d", status)
}

func (c *Client) QueryExpert(ctx context.Context, req apiv1.QueryRequest, requestID string, xTenantId string, xProjectId string) (*apiv1.QueryResponse, *apiv1.Problem, error) {
	path := "/v1/assistant/query"
	headers := map[string]string{}
	if requestID != "" {
		headers["X-Request-Id"] = requestID
	}
	status, body, problem, err := c.doJSON(ctx, "POST", path, req, headers)
	if err != nil {
		return nil, nil, err
	}
	if status == http.StatusOK {
		var outBody apiv1.QueryResponse
		if err := json.Unmarshal(body, &outBody); err != nil {
			return nil, nil, fmt.Errorf("decode success response: %w", err)
		}
		return &outBody, nil, nil
	}
	if problem != nil {
		return nil, problem, nil
	}
	return nil, nil, fmt.Errorf("unexpected status code: %d", status)
}

func (c *Client) GetExpertCapabilities(ctx context.Context, requestID string, xTenantId string, xProjectId string) (*apiv1.ExpertCapabilitiesResponse, *apiv1.Problem, error) {
	path := "/v1/assistant/experts"
	headers := map[string]string{}
	if requestID != "" {
		headers["X-Request-Id"] = requestID
	}
	status, body, problem, err := c.doJSON(ctx, "GET", path, nil, headers)
	if err != nil {
		return nil, nil, err
	}
	if status == http.StatusOK {
		var outBody apiv1.ExpertCapabilitiesResponse
		if err := json.Unmarshal(body, &outBody); err != nil {
			return nil, nil, fmt.Errorf("decode success response: %w", err)
		}
		return &outBody, nil, nil
	}
	if problem != nil {
		return nil, problem, nil
	}
	return nil, nil, fmt.Errorf("unexpected status code: %d", status)
}

func (c *Client) doJSON(ctx context.Context, method, path string, reqBody any, headers map[string]string) (int, []byte, *apiv1.Problem, error) {
	var bodyReader io.Reader
	if reqBody != nil {
		buf, err := json.Marshal(reqBody)
		if err != nil {
			return 0, nil, nil, fmt.Errorf("encode request body: %w", err)
		}
		bodyReader = bytes.NewReader(buf)
	}

	req, err := http.NewRequestWithContext(ctx, method, c.BaseURL+path, bodyReader)
	if err != nil {
		return 0, nil, nil, fmt.Errorf("build request: %w", err)
	}
	if reqBody != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	req.Header.Set("Accept", "application/json, application/problem+json")
	if c.Token != "" {
		req.Header.Set("Authorization", "Bearer "+c.Token)
	}
	for k, v := range headers {
		if strings.TrimSpace(v) != "" {
			req.Header.Set(k, v)
		}
	}

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return 0, nil, nil, fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return 0, nil, nil, fmt.Errorf("read response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var problem apiv1.Problem
		if err := json.Unmarshal(respBody, &problem); err == nil && strings.TrimSpace(problem.Title) != "" {
			return resp.StatusCode, respBody, &problem, nil
		}
	}
	return resp.StatusCode, respBody, nil, nil
}
