#!/usr/bin/env python3
"""
Offline OpenAPI -> Go stub generator for COVA.

Generates:
  - pkg/apiv1/types_gen.go
  - internal/api/openapi/server_gen.go
  - sdk/go/cova/client_gen.go
"""

from __future__ import annotations

import argparse
import pathlib
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

import yaml


def to_camel(name: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", name)
    out = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if out and out[0].isdigit():
        out = "N" + out
    return out or "X"


def lower_camel(name: str) -> str:
    c = to_camel(name)
    return c[:1].lower() + c[1:] if c else c


def ref_name(ref: str) -> str:
    return ref.split("/")[-1]


def quote_go(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def go_scalar_type(schema: Dict[str, Any]) -> str:
    typ = schema.get("type")
    if typ == "string":
        return "string"
    if typ == "integer":
        return "int"
    if typ == "number":
        return "float64"
    if typ == "boolean":
        return "bool"
    if typ == "array":
        return f"[]{go_type(schema.get('items', {}), for_field=False)}"
    if typ == "object":
        ap = schema.get("additionalProperties")
        if ap is True or ap is None:
            return "map[string]any"
        if isinstance(ap, dict):
            return f"map[string]{go_type(ap, for_field=False)}"
        return "map[string]any"
    return "any"


def go_type(schema: Dict[str, Any], *, for_field: bool, required: bool = True) -> str:
    if "$ref" in schema:
        base = ref_name(schema["$ref"])
    elif "allOf" in schema:
        all_of = schema["allOf"]
        if len(all_of) == 1 and "$ref" in all_of[0]:
            base = ref_name(all_of[0]["$ref"])
        else:
            base = "any"
    else:
        base = go_scalar_type(schema)

    nullable = bool(schema.get("nullable", False))
    if for_field and (nullable or not required):
        if base.startswith("[]") or base.startswith("map[") or base == "any":
            return base
        return "*" + base
    return base


def emit_header(buf: List[str], note: str) -> None:
    buf.append("// Code generated by scripts/generate_openapi_go.py. DO NOT EDIT.")
    buf.append(f"// {note}")
    buf.append("")


def render_struct_fields(properties: Dict[str, Any], required: List[str]) -> List[str]:
    lines: List[str] = []
    required_set = set(required or [])
    for prop_name, prop_schema in properties.items():
        field_name = to_camel(prop_name)
        field_type = go_type(prop_schema, for_field=True, required=prop_name in required_set)
        tag = prop_name
        if prop_name not in required_set:
            tag += ",omitempty"
        lines.append(f"\t{field_name} {field_type} `json:\"{tag}\"`")
    return lines


def generate_types(spec: Dict[str, Any]) -> str:
    schemas = spec.get("components", {}).get("schemas", {})
    out: List[str] = []
    emit_header(out, "Source: docs/openapi.v1.yaml")
    out.append("package apiv1")
    out.append("")

    for schema_name, schema in schemas.items():
        if "enum" in schema:
            out.append(f"type {schema_name} string")
            out.append("")
            out.append("const (")
            for value in schema["enum"]:
                const_name = f"{schema_name}{to_camel(str(value))}"
                out.append(f"\t{const_name} {schema_name} = {quote_go(str(value))}")
            out.append(")")
            out.append("")
            continue

        if "allOf" in schema:
            all_of = schema["allOf"]
            if len(all_of) == 1 and "$ref" in all_of[0]:
                out.append(f"type {schema_name} = {ref_name(all_of[0]['$ref'])}")
                out.append("")
                continue

        typ = schema.get("type")
        if typ == "object":
            props = schema.get("properties", {})
            required = schema.get("required", [])
            add_props = schema.get("additionalProperties")
            if not props and add_props is True:
                out.append(f"type {schema_name} map[string]any")
                out.append("")
                continue
            if not props and isinstance(add_props, dict):
                map_type = go_type(add_props, for_field=False)
                out.append(f"type {schema_name} map[string]{map_type}")
                out.append("")
                continue

            out.append(f"type {schema_name} struct {{")
            fields = render_struct_fields(props, required)
            if fields:
                out.extend(fields)
            out.append("}")
            out.append("")
            continue

        if typ == "array":
            arr_type = go_type(schema.get("items", {}), for_field=False)
            out.append(f"type {schema_name} []{arr_type}")
            out.append("")
            continue

        if typ in ("string", "integer", "number", "boolean"):
            out.append(f"type {schema_name} {go_scalar_type(schema)}")
            out.append("")
            continue

        out.append(f"type {schema_name} any")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


@dataclass
class Operation:
    method: str
    path: str
    operation_id: str
    request_ref: Optional[str]
    success_status: int
    success_ref: Optional[str]
    parameters: List[Tuple[str, str]]  # (name, in)

    @property
    def method_name(self) -> str:
        return to_camel(self.operation_id)

    @property
    def params_type(self) -> str:
        return f"{self.method_name}Params"


def collect_operations(spec: Dict[str, Any]) -> List[Operation]:
    out: List[Operation] = []
    components_params = spec.get("components", {}).get("parameters", {})
    paths = spec.get("paths", {})

    for path, path_item in paths.items():
        for method in ("get", "post", "put", "patch", "delete"):
            if method not in path_item:
                continue
            op = path_item[method]
            op_id = op.get("operationId")
            if not op_id:
                continue

            request_ref = None
            request_body = op.get("requestBody", {})
            content = request_body.get("content", {})
            app_json = content.get("application/json", {})
            schema = app_json.get("schema", {})
            if "$ref" in schema:
                request_ref = ref_name(schema["$ref"])

            success_status = 200
            success_ref = None
            responses = op.get("responses", {})
            for status_code in sorted(responses.keys(), key=lambda x: int(x) if x.isdigit() else 999):
                if not status_code.isdigit():
                    continue
                code_num = int(status_code)
                if 200 <= code_num < 300:
                    success_status = code_num
                    media = responses[status_code].get("content", {})
                    schema_obj = media.get("application/json", {}).get("schema")
                    if isinstance(schema_obj, dict) and "$ref" in schema_obj:
                        success_ref = ref_name(schema_obj["$ref"])
                    break

            params: List[Tuple[str, str]] = []
            raw_params = []
            raw_params.extend(path_item.get("parameters", []))
            raw_params.extend(op.get("parameters", []))
            for p in raw_params:
                resolved = p
                if "$ref" in p:
                    resolved = components_params[ref_name(p["$ref"])]
                params.append((resolved["name"], resolved["in"]))

            out.append(
                Operation(
                    method=method.upper(),
                    path=path,
                    operation_id=op_id,
                    request_ref=request_ref,
                    success_status=success_status,
                    success_ref=success_ref,
                    parameters=params,
                )
            )
    return out


def go_param_field(name: str) -> str:
    if name == "job_id":
        return "JobID"
    return to_camel(name)


def generate_server(spec: Dict[str, Any]) -> str:
    ops = collect_operations(spec)
    out: List[str] = []
    emit_header(out, "Source: docs/openapi.v1.yaml")
    out.append("package openapi")
    out.append("")
    out.append("import (")
    out.append('\t"context"')
    out.append('\t"encoding/json"')
    out.append('\t"errors"')
    out.append('\t"net/http"')
    out.append('\t"strings"')
    out.append("")
    out.append('\t"cova/pkg/apiv1"')
    out.append(")")
    out.append("")

    for op in ops:
        out.append(f"type {op.params_type} struct {{")
        for pname, _pin in op.parameters:
            field = go_param_field(pname)
            out.append(f"\t{field} string")
        out.append("}")
        out.append("")

    out.append("type ServerInterface interface {")
    for op in ops:
        if op.request_ref:
            out.append(
                f"\t{op.method_name}(ctx context.Context, params {op.params_type}, req apiv1.{op.request_ref}) (int, any, error)"
            )
        else:
            out.append(f"\t{op.method_name}(ctx context.Context, params {op.params_type}) (int, any, error)")
    out.append("}")
    out.append("")

    out.append("type Handler struct {")
    out.append("\timpl ServerInterface")
    out.append("}")
    out.append("")
    out.append("func NewHandler(impl ServerInterface) http.Handler {")
    out.append("\treturn &Handler{impl: impl}")
    out.append("}")
    out.append("")

    out.append("func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {")
    out.append("\tfor _, route := range routes {")
    out.append("\t\tif r.Method != route.method {")
    out.append("\t\t\tcontinue")
    out.append("\t\t}")
    out.append("\t\tpathParams, ok := matchPath(route.path, r.URL.Path)")
    out.append("\t\tif !ok {")
    out.append("\t\t\tcontinue")
    out.append("\t\t}")
    out.append("\t\th.dispatch(route.operation, w, r, pathParams)")
    out.append("\t\treturn")
    out.append("\t}")
    out.append("\thttp.NotFound(w, r)")
    out.append("}")
    out.append("")

    out.append("func (h *Handler) dispatch(operation string, w http.ResponseWriter, r *http.Request, pathParams map[string]string) {")
    out.append("\tctx := r.Context()")
    out.append("\trequestID := strings.TrimSpace(r.Header.Get(\"X-Request-Id\"))")
    out.append("\tswitch operation {")
    for op in ops:
        out.append(f"\tcase {quote_go(op.operation_id)}:")
        out.append(f"\t\tparams := {op.params_type}{{")
        for pname, pin in op.parameters:
            field = go_param_field(pname)
            if pin == "path":
                out.append(f"\t\t\t{field}: pathParams[{quote_go(pname)}],")
            elif pin == "header":
                out.append(f"\t\t\t{field}: strings.TrimSpace(r.Header.Get({quote_go(pname)})),")
        out.append("\t\t}")
        if op.request_ref:
            out.append(f"\t\tvar req apiv1.{op.request_ref}")
            out.append("\t\tif err := json.NewDecoder(r.Body).Decode(&req); err != nil {")
            out.append("\t\t\twriteProblem(w, http.StatusBadRequest, apiv1.Problem{")
            out.append('\t\t\t\tType: "https://api.cova.example.com/errors/invalid-request",')
            out.append('\t\t\t\tTitle: "Invalid request",')
            out.append("\t\t\t\tStatus: http.StatusBadRequest,")
            out.append('\t\t\t\tDetail: stringPtr("request body must be valid JSON"),')
            out.append("\t\t\t\tInstance: stringPtr(r.URL.Path),")
            out.append("\t\t\t\tRequestId: stringPtr(requestID),")
            out.append("\t\t\t})")
            out.append("\t\t\treturn")
            out.append("\t\t}")
            out.append(f"\t\tstatus, body, err := h.impl.{op.method_name}(ctx, params, req)")
        else:
            out.append(f"\t\tstatus, body, err := h.impl.{op.method_name}(ctx, params)")
        out.append("\t\tif err != nil {")
        out.append("\t\t\tif errors.Is(err, ErrUnimplemented) {")
        out.append("\t\t\t\twriteProblem(w, http.StatusNotImplemented, apiv1.Problem{")
        out.append('\t\t\t\t\tType: "https://api.cova.example.com/errors/not-implemented",')
        out.append('\t\t\t\t\tTitle: "Not implemented",')
        out.append("\t\t\t\t\tStatus: http.StatusNotImplemented,")
        out.append('\t\t\t\t\tDetail: stringPtr("operation is not implemented"),')
        out.append("\t\t\t\t\tInstance: stringPtr(r.URL.Path),")
        out.append("\t\t\t\t\tRequestId: stringPtr(requestID),")
        out.append("\t\t\t\t})")
        out.append("\t\t\t\treturn")
        out.append("\t\t\t}")
        out.append("\t\t\twriteProblem(w, http.StatusInternalServerError, apiv1.Problem{")
        out.append('\t\t\t\tType: "https://api.cova.example.com/errors/internal-error",')
        out.append('\t\t\t\tTitle: "Internal error",')
        out.append("\t\t\t\tStatus: http.StatusInternalServerError,")
        out.append("\t\t\t\tDetail: stringPtr(err.Error()),")
        out.append("\t\t\t\tInstance: stringPtr(r.URL.Path),")
        out.append("\t\t\t\tRequestId: stringPtr(requestID),")
        out.append("\t\t\t})")
        out.append("\t\t\treturn")
        out.append("\t\t}")
        out.append("\t\twriteResponse(w, status, body)")
        out.append("\t\treturn")
    out.append("\tdefault:")
    out.append("\t\thttp.NotFound(w, r)")
    out.append("\t}")
    out.append("}")
    out.append("")

    out.append("var ErrUnimplemented = errors.New(\"operation not implemented\")")
    out.append("")

    out.append("type route struct {")
    out.append("\tmethod    string")
    out.append("\tpath      string")
    out.append("\toperation string")
    out.append("}")
    out.append("")
    out.append("var routes = []route{")
    for op in ops:
        out.append(f"\t{{method: {quote_go(op.method)}, path: {quote_go(op.path)}, operation: {quote_go(op.operation_id)}}},")
    out.append("}")
    out.append("")

    out.append("func matchPath(pattern, actual string) (map[string]string, bool) {")
    out.append("\tpatternParts := splitPath(pattern)")
    out.append("\tactualParts := splitPath(actual)")
    out.append("\tif len(patternParts) != len(actualParts) {")
    out.append("\t\treturn nil, false")
    out.append("\t}")
    out.append("\tparams := make(map[string]string)")
    out.append("\tfor i := range patternParts {")
    out.append("\t\tp := patternParts[i]")
    out.append("\t\ta := actualParts[i]")
    out.append('\t\tif strings.HasPrefix(p, "{") && strings.HasSuffix(p, "}") {')
    out.append("\t\t\tkey := strings.TrimSuffix(strings.TrimPrefix(p, \"{\"), \"}\")")
    out.append("\t\t\tparams[key] = a")
    out.append("\t\t\tcontinue")
    out.append("\t\t}")
    out.append("\t\tif p != a {")
    out.append("\t\t\treturn nil, false")
    out.append("\t\t}")
    out.append("\t}")
    out.append("\treturn params, true")
    out.append("}")
    out.append("")

    out.append("func splitPath(path string) []string {")
    out.append("\ttrimmed := strings.Trim(path, \"/\")")
    out.append("\tif trimmed == \"\" {")
    out.append("\t\treturn []string{}")
    out.append("\t}")
    out.append("\treturn strings.Split(trimmed, \"/\")")
    out.append("}")
    out.append("")

    out.append("func stringPtr(v string) *string {")
    out.append("\treturn &v")
    out.append("}")
    out.append("")

    out.append("func writeProblem(w http.ResponseWriter, status int, p apiv1.Problem) {")
    out.append('\tw.Header().Set("Content-Type", "application/problem+json")')
    out.append("\tw.WriteHeader(status)")
    out.append("\t_ = json.NewEncoder(w).Encode(p)")
    out.append("}")
    out.append("")

    out.append("func writeResponse(w http.ResponseWriter, status int, body any) {")
    out.append("\tif body == nil {")
    out.append("\t\tw.WriteHeader(status)")
    out.append("\t\treturn")
    out.append("\t}")
    out.append("\tif status >= 400 {")
    out.append('\t\tw.Header().Set("Content-Type", "application/problem+json")')
    out.append("\t} else {")
    out.append('\t\tw.Header().Set("Content-Type", "application/json")')
    out.append("\t}")
    out.append("\tw.WriteHeader(status)")
    out.append("\t_ = json.NewEncoder(w).Encode(body)")
    out.append("}")
    out.append("")

    return "\n".join(out).rstrip() + "\n"


def go_status_name(code: int) -> str:
    if code == 200:
        return "OK"
    if code == 202:
        return "Accepted"
    if code == 204:
        return "NoContent"
    return f"Status{code}"


def path_format(path: str) -> Tuple[str, List[str]]:
    fields = re.findall(r"{([^}]+)}", path)
    fmt_path = re.sub(r"{[^}]+}", "%s", path)
    return fmt_path, fields


def generate_client(spec: Dict[str, Any]) -> str:
    ops = collect_operations(spec)
    out: List[str] = []
    emit_header(out, "Source: docs/openapi.v1.yaml")
    out.append("package cova")
    out.append("")
    out.append("import (")
    out.append('\t"bytes"')
    out.append('\t"context"')
    out.append('\t"encoding/json"')
    out.append('\t"fmt"')
    out.append('\t"io"')
    out.append('\t"net/http"')
    out.append('\t"net/url"')
    out.append('\t"strings"')
    out.append("")
    out.append('\t"cova/pkg/apiv1"')
    out.append(")")
    out.append("")
    out.append("type Client struct {")
    out.append("\tBaseURL    string")
    out.append("\tHTTPClient *http.Client")
    out.append("\tToken      string")
    out.append("}")
    out.append("")
    out.append("type ClientOption func(*Client)")
    out.append("")
    out.append("func WithHTTPClient(httpClient *http.Client) ClientOption {")
    out.append("\treturn func(c *Client) {")
    out.append("\t\tif httpClient != nil {")
    out.append("\t\t\tc.HTTPClient = httpClient")
    out.append("\t\t}")
    out.append("\t}")
    out.append("}")
    out.append("")
    out.append("func WithBearerToken(token string) ClientOption {")
    out.append("\treturn func(c *Client) { c.Token = token }")
    out.append("}")
    out.append("")
    out.append("func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {")
    out.append("\tbaseURL = strings.TrimSpace(baseURL)")
    out.append("\tif baseURL == \"\" {")
    out.append('\t\treturn nil, fmt.Errorf("baseURL is required")')
    out.append("\t}")
    out.append("\tu, err := url.Parse(baseURL)")
    out.append("\tif err != nil {")
    out.append('\t\treturn nil, fmt.Errorf("invalid baseURL: %w", err)')
    out.append("\t}")
    out.append("\tc := &Client{")
    out.append("\t\tBaseURL:    strings.TrimRight(u.String(), \"/\"),")
    out.append("\t\tHTTPClient: http.DefaultClient,")
    out.append("\t}")
    out.append("\tfor _, opt := range opts {")
    out.append("\t\topt(c)")
    out.append("\t}")
    out.append("\tif c.HTTPClient == nil {")
    out.append("\t\tc.HTTPClient = http.DefaultClient")
    out.append("\t}")
    out.append("\treturn c, nil")
    out.append("}")
    out.append("")

    for op in ops:
        success_type = "any"
        if op.success_ref:
            success_type = f"apiv1.{op.success_ref}"
        fields = [p for p, pin in op.parameters if pin == "path"]
        header_fields = [p for p, pin in op.parameters if pin == "header"]
        args: List[str] = ["ctx context.Context"]
        for f in fields:
            args.append(f"{lower_camel(go_param_field(f))} string")
        if op.request_ref:
            args.append(f"req apiv1.{op.request_ref}")
        for hf in header_fields:
            if hf == "X-Request-Id":
                args.append("requestID string")
            elif hf == "Idempotency-Key":
                args.append("idempotencyKey string")
            else:
                args.append(f"{lower_camel(go_param_field(hf))} string")
        sig_args = ", ".join(args)

        out.append(
            f"func (c *Client) {op.method_name}({sig_args}) (*{success_type}, *apiv1.Problem, error) {{"
        )
        fmt_path, pf = path_format(op.path)
        if pf:
            fmt_args = ", ".join([lower_camel(go_param_field(x)) for x in pf])
            out.append(f"\tpath := fmt.Sprintf({quote_go(fmt_path)}, {fmt_args})")
        else:
            out.append(f"\tpath := {quote_go(op.path)}")
        out.append("\theaders := map[string]string{}")
        for hf in header_fields:
            if hf == "X-Request-Id":
                out.append("\tif requestID != \"\" {")
                out.append('\t\theaders["X-Request-Id"] = requestID')
                out.append("\t}")
            elif hf == "Idempotency-Key":
                out.append("\tif idempotencyKey != \"\" {")
                out.append('\t\theaders["Idempotency-Key"] = idempotencyKey')
                out.append("\t}")
        body_arg = "nil"
        if op.request_ref:
            body_arg = "req"
        out.append(
            f"\tstatus, body, problem, err := c.doJSON(ctx, {quote_go(op.method)}, path, {body_arg}, headers)"
        )
        out.append("\tif err != nil {")
        out.append("\t\treturn nil, nil, err")
        out.append("\t}")
        out.append(f"\tif status == http.Status{go_status_name(op.success_status)} {{")
        out.append(f"\t\tvar outBody {success_type}")
        out.append("\t\tif err := json.Unmarshal(body, &outBody); err != nil {")
        out.append('\t\t\treturn nil, nil, fmt.Errorf("decode success response: %w", err)')
        out.append("\t\t}")
        out.append("\t\treturn &outBody, nil, nil")
        out.append("\t}")
        out.append("\tif problem != nil {")
        out.append("\t\treturn nil, problem, nil")
        out.append("\t}")
        out.append('\treturn nil, nil, fmt.Errorf("unexpected status code: %d", status)')
        out.append("}")
        out.append("")

    out.append(
        "func (c *Client) doJSON(ctx context.Context, method, path string, reqBody any, headers map[string]string) (int, []byte, *apiv1.Problem, error) {"
    )
    out.append("\tvar bodyReader io.Reader")
    out.append("\tif reqBody != nil {")
    out.append("\t\tbuf, err := json.Marshal(reqBody)")
    out.append("\t\tif err != nil {")
    out.append('\t\t\treturn 0, nil, nil, fmt.Errorf("encode request body: %w", err)')
    out.append("\t\t}")
    out.append("\t\tbodyReader = bytes.NewReader(buf)")
    out.append("\t}")
    out.append("")
    out.append('\treq, err := http.NewRequestWithContext(ctx, method, c.BaseURL+path, bodyReader)')
    out.append("\tif err != nil {")
    out.append('\t\treturn 0, nil, nil, fmt.Errorf("build request: %w", err)')
    out.append("\t}")
    out.append("\tif reqBody != nil {")
    out.append('\t\treq.Header.Set("Content-Type", "application/json")')
    out.append("\t}")
    out.append('\treq.Header.Set("Accept", "application/json, application/problem+json")')
    out.append("\tif c.Token != \"\" {")
    out.append('\t\treq.Header.Set("Authorization", "Bearer "+c.Token)')
    out.append("\t}")
    out.append("\tfor k, v := range headers {")
    out.append("\t\tif strings.TrimSpace(v) != \"\" {")
    out.append("\t\t\treq.Header.Set(k, v)")
    out.append("\t\t}")
    out.append("\t}")
    out.append("")
    out.append("\tresp, err := c.HTTPClient.Do(req)")
    out.append("\tif err != nil {")
    out.append('\t\treturn 0, nil, nil, fmt.Errorf("send request: %w", err)')
    out.append("\t}")
    out.append("\tdefer resp.Body.Close()")
    out.append("")
    out.append("\trespBody, err := io.ReadAll(resp.Body)")
    out.append("\tif err != nil {")
    out.append('\t\treturn 0, nil, nil, fmt.Errorf("read response body: %w", err)')
    out.append("\t}")
    out.append("")
    out.append("\tif resp.StatusCode >= 400 {")
    out.append("\t\tvar problem apiv1.Problem")
    out.append("\t\tif err := json.Unmarshal(respBody, &problem); err == nil && strings.TrimSpace(problem.Title) != \"\" {")
    out.append("\t\t\treturn resp.StatusCode, respBody, &problem, nil")
    out.append("\t\t}")
    out.append("\t}")
    out.append("\treturn resp.StatusCode, respBody, nil, nil")
    out.append("}")
    out.append("")

    return "\n".join(out).rstrip() + "\n"


def write_file(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Go stubs from OpenAPI file")
    parser.add_argument("--spec", default="docs/openapi.v1.yaml")
    parser.add_argument("--root", default=".")
    args = parser.parse_args()

    root = pathlib.Path(args.root).resolve()
    spec_path = root / args.spec
    spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))

    types_go = generate_types(spec)
    server_go = generate_server(spec)
    client_go = generate_client(spec)

    write_file(root / "pkg" / "apiv1" / "types_gen.go", types_go)
    write_file(root / "internal" / "api" / "openapi" / "server_gen.go", server_go)
    write_file(root / "sdk" / "go" / "cova" / "client_gen.go", client_go)


if __name__ == "__main__":
    main()
